'use client';

import React, { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import PerformerCard from "../../../components/PerformerCard";

type MediaItem = {
  id: number;
  rel_path: string;
  kind: string;
  ext?: string | null;
  size?: number | null;
  mtime?: number | null;
};

export default function PerformerDetail({ params }: { params: { id: string } }) {
  const router = useRouter();

  const [p, setP] = useState<any>(null);
  const [items, setItems] = useState<MediaItem[]>([]);
  const [linkedMedia, setLinkedMedia] = useState<any[]>([]);
  const [err, setErr] = useState("");
  const [playing, setPlaying] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setErr("");
      try {
        const res = await fetch(`/api/performers/${params.id}`, { cache: "no-store" });
        if (!res.ok) throw new Error(await res.text());
        const data = await res.json();
        if (cancelled) return;
        setP(data);

        const linkedRes = await fetch(`/api/performers/${params.id}/media`, { cache: "no-store" });
        if (linkedRes.ok) {
          const linked = await linkedRes.json();
          if (cancelled) return;
          setLinkedMedia(Array.isArray(linked) ? linked : []);
        }

        const itemsRes = await fetch(`/api/media/items?limit=500&offset=0`, { cache: "no-store" });
        if (itemsRes.ok) {
          const raw = await itemsRes.json();
          if (cancelled) return;
          setItems(Array.isArray(raw) ? raw : []);
        }
      } catch (e: any) {
        if (cancelled) return;
        setErr(e?.message || String(e));
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [params.id]);

  const matches = useMemo(() => {
    // Prefer server-side matching (performer_media). Fallback to old heuristic if empty.
    if (linkedMedia && linkedMedia.length) {
      return linkedMedia.map((x: any) => ({ ...(x.media || {}), confidence: x.confidence, matched_by: x.matched_by }));
    }
    if (!p?.name) return [];
    const needle = String(p.name).toLowerCase();
    const first = needle.split(" ")[0] || needle;
    return items.filter((x) => String(x.rel_path || "").toLowerCase().includes(first)).slice(0, 60);
  }, [items, p, linkedMedia]);

  return (
    <main style={{ padding: 24, maxWidth: 1200, margin: "0 auto" }}>
      <a href="/" style={{ textDecoration: "none", color: "black", opacity: 0.75 }}>
        ← Back
      </a>

      {err ? (
        <div
          style={{
            marginTop: 12,
            padding: 12,
            border: "1px solid rgba(255,0,0,0.25)",
            background: "rgba(255,0,0,0.05)",
            borderRadius: 12,
            whiteSpace: "pre-wrap",
          }}
        >
          {err}
        </div>
      ) : null}

      {p ? (
        <div style={{ marginTop: 16 }}>
          <PerformerCard p={p} variant="detail" />

          <h2 style={{ marginTop: 24 }}>Indexed files (best-effort match)</h2>
          <div style={{ opacity: 0.7, fontSize: 13, marginBottom: 10 }}>
            Thumbnails are generated by the API using <code>ffmpeg</code> for videos and cached.
          </div>

          {matches.length ? (
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))", gap: 14 }}>
              {matches.map((m) => (
                <div
                  key={m.id}
                  style={{
                    border: "none",
                    borderRadius: 16,
                    overflow: "hidden",
                    background: "white",
                    boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
                    transition: "all 0.2s",
                    cursor: m.kind === "video" ? "pointer" : "default",
                  }}
                  onClick={() => {
                    if (m.kind === "video") {
                      setPlaying(m.rel_path);
                    }
                  }}
                  onMouseEnter={(e) => {
                    if (m.kind === "video") {
                      e.currentTarget.style.transform = "translateY(-2px)";
                      e.currentTarget.style.boxShadow = "0 4px 20px rgba(0,0,0,0.12)";
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (m.kind === "video") {
                      e.currentTarget.style.transform = "translateY(0)";
                      e.currentTarget.style.boxShadow = "0 2px 12px rgba(0,0,0,0.08)";
                    }
                  }}
                >
                  <div
                    style={{
                      aspectRatio: "16/10",
                      background: "linear-gradient(135deg, rgba(0,0,0,0.03), rgba(0,0,0,0.06))",
                      position: "relative",
                      display: "grid",
                      placeItems: "center",
                    }}
                  >
                    <img
                      src={`/api/media/thumb?rel_path=${encodeURIComponent(m.rel_path)}`}
                      alt={m.rel_path}
                      style={{ width: "100%", height: "100%", objectFit: "cover" }}
                      onError={(e) => {
                        (e.currentTarget as HTMLImageElement).style.display = "none";
                      }}
                    />
                    {m.kind === "video" && (
                      <div
                        style={{
                          position: "absolute",
                          top: "50%",
                          left: "50%",
                          transform: "translate(-50%, -50%)",
                          width: 48,
                          height: 48,
                          borderRadius: "50%",
                          background: "rgba(102, 126, 234, 0.9)",
                          display: "grid",
                          placeItems: "center",
                          color: "white",
                          fontSize: 20,
                        }}
                      >
                        ▶
                      </div>
                    )}
                    <div
                      style={{
                        position: "absolute",
                        bottom: 8,
                        right: 8,
                        fontSize: 10,
                        padding: "4px 8px",
                        borderRadius: 8,
                        background: "rgba(0,0,0,0.75)",
                        color: "white",
                        fontWeight: 600,
                        textTransform: "uppercase",
                      }}
                    >
                      {m.kind}
                    </div>
                  </div>

                  <div
                    style={{
                      padding: 12,
                      fontSize: 11,
                      fontFamily: "ui-monospace, SFMono-Regular",
                      opacity: 0.7,
                      wordBreak: "break-word",
                      lineHeight: 1.4,
                    }}
                  >
                    {m.rel_path.split("/").pop()}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div style={{ padding: 24, opacity: 0.6, fontSize: 14, border: "2px dashed rgba(0,0,0,0.1)", borderRadius: 16, textAlign: "center" }}>
              No matches yet. Use <b>Tools → Index now</b> to build the media index.
            </div>
          )}

          {playing && (
            <div
              onClick={() => setPlaying(null)}
              style={{
                position: "fixed",
                inset: 0,
                background: "rgba(0,0,0,0.9)",
                display: "grid",
                placeItems: "center",
                padding: 24,
                zIndex: 9999,
                cursor: "pointer",
              }}
            >
              <div
                onClick={(e) => e.stopPropagation()}
                style={{
                  position: "relative",
                  maxWidth: "90vw",
                  maxHeight: "90vh",
                  borderRadius: 16,
                  overflow: "hidden",
                  boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
                  cursor: "default",
                }}
              >
                <button
                  onClick={() => setPlaying(null)}
                  style={{
                    position: "absolute",
                    top: 16,
                    right: 16,
                    width: 40,
                    height: 40,
                    borderRadius: "50%",
                    border: "none",
                    background: "rgba(0,0,0,0.7)",
                    color: "white",
                    fontSize: 20,
                    cursor: "pointer",
                    zIndex: 10,
                  }}
                >
                  ✕
                </button>
                <video
                  src={`/api/media/stream?rel_path=${encodeURIComponent(playing)}`}
                  controls
                  autoPlay
                  style={{
                    maxWidth: "90vw",
                    maxHeight: "90vh",
                    display: "block",
                  }}
                />
              </div>
            </div>
          )}
        </div>
      ) : (
        <div style={{ marginTop: 16, opacity: 0.7 }}>Loading…</div>
      )}
    </main>
  );
}